### ISSUE TITLE
Need ability to support ISO 8601 patterns in LocalTime TypeConverter

### ISSUE THREAD

**Issue by jsearles** [nodatime/nodatime#1725] opened 2022-11-10 15:59 UTC
Right now, the `TypeConverter` associated with `LocalTime` requires the precision to at least include seconds. I'm looking to support text with a pattern of `HH':'mm` which is a valid ISO 8601 pattern.

Specifically, the problem I am facing is that since the `LocalTime` is decorated with the specific `TypeConverter` I am not finding a clean way to replace it. Is there a way to configure the patterns supported by a given `TypeConverter`? Or perhaps a way to replace the registered TypeConverters that I am missing?

I believe this is related to issue https://github.com/nodatime/nodatime/issues/607

**Comment by jsearles** [comment] 2022-11-18 03:49
Actually I have no issue with the formatting. I prefer that the seconds are included. The problem I have is we are using [JSJoda](https://github.com/js-joda/js-joda) on the client side and using their implementation of LocalTime excludes the seconds if they are zero.

```js
JSJoda.LocalTime.parse("03:00:00").toJSON();
> '03:00'
```

**Comment by jsearles** [comment] 2022-11-18 03:52
Also, I have no issue with using a custom type converter - I just don't see a good way to override the built-in converter since it is applied via an attribute.

**Comment by jskeet** [comment] 2022-11-18 07:40
> Also, I have no issue with using a custom type converter - I just don't see a good way to override the built-in converter since it is applied via an attribute.

Well you've still told us *nothing* about how your context. No, there's no way of changing the default converter. There may very well be a way of specifying a different one, but we won't be able to help you find that way without knowing what kind of app you're writing.

I don't expect to change the default converter, so you should really be focusing on working out how to specify a custom one in your context.

**Comment by malcolmr** [comment] 2022-11-18 09:05
Context would be useful, yes.

The `TypeConverter` API is horrible, so the only way I can see to introduce flexibility here would be to allow statically configuring our existing converters to replace the default pattern (either via `TypeConverterSettings` or `TypeConverterBase`).

Though — as well as making this mess even more complex — it's not obvious whether that would actually help in some cases, since I'm not sure you always have the ability to run code in the context of the process doing the (de)serialisation.

**Comment by jsearles** [comment] 2022-11-18 17:29
@malcolmr - yes, those approaches would help - I agree. This is the only way that I see to make it configurable. That or remove the attribute from the types and add a helper method to wire them up for the default case. Or make this the default behavior. Probably the first approach is the right mix of configuration without breaking changes.

I'm not sure what more context I can provide. The app is an ERP application. The LocalTime can be a shift schedule, it can be an event time - there are dozens if not hundreds of use cases. The problem is that the client library (JSJoda) is serializing these values to HH:mm when seconds are zero. This then fails to populate the model correctly in asp.net model binding. (This is full-framework MVC, though I except the same thing would happen in Core.)

FWIW, I have been able to replace the type converter registration, but the approach is so convoluted that I'm wary of using it. It involved creating a custom TypeDescriptionProvider that wraps the resolved value for LocalTime and then calling through all methods/properties except for the ones that return a TypeConverter.

**Comment by jskeet** [comment] 2022-11-18 17:37
> This is full-framework MVC, though I except the same thing would happen in Core.

That's the sort of context we were missing. We didn't even know it was a web app. It would be more helpful if you'd provide a minimal but complete example so we could reproduce it for ourselves, mind you.

It's still not clear what you expect Noda Time to do though. You say:

> This is the only way that I see to make it configurable. That or remove the attribute from the types and add a helper method to wire them up for the default case. Or make this the default behavior. Probably the first approach is the right mix of configuration without breaking changes.

What sort of "helper method" are you thinking about? Noda Time doesn't do *anything* apart from provide the attributes, because that's what the type converter framework (as part of .NET, not Noda Time) expects. It's the framework that's being inflexible here, by not providing any sort of configuration.

I haven't used TypeConverter in ASP.NET MVC personally, but I'd *expect* there to be a way of overriding the binding rules there. But as it would take me a significant amount of time to reproduce this, having to guess at what your code looks like, I don't think there's anything more to be done here.

Please provide either an example that we can use to investigate further, or *concrete* suggestions of what you'd expect a change in Noda Time to look like. This isn't the right repo to request the TypeConverter discovery mechanisms to be more configurable, as that's not part of Noda Time.

**Comment by jsearles** [comment] 2022-11-18 18:01
Model binding uses TypeConverters so if you've used model binding for a model that has a LocalTime you used the TypeConverter. Sorry for not providing more context up front - I guess I was fixated on the solution.

My ideal scenario would be that NodaTime would update the converter to support parsing this format, as it is valid according to the spec.

Using a pattern like this for the LocalTimeTypeConverter maybe:

```csharp
      var localPattern = new CompositePatternBuilder<LocalTime>
      {
        { LocalTimePattern.ExtendedIso, _ => true },  // use this pattern for formatting
        { LocalTimePattern.CreateWithInvariantCulture("HH':'mm"), _ => false }
      }.Build();
```

As for helper, before NodaTime v3 the type converters were not applied to the models, so at runtime we could do something like this:

```csharp
TypeDescriptor.AddAttributes(typeof(LocalTime), new[] { new TypeConverterAttribute(typeof(LocalTimeTypeConverter)) });
```

So one solution would be to remove the TypeConverter from the types and provide a helper for bootstrapping. Then consumers could opt out. I understand this would be a breaking change so it's probably a non-starter.

I understand that type converters are difficult to work with, etc - and there's nothing that your library could do about that. Just looking for the best solution.

I will work on getting a minimal reproduction for this.

**Comment by jskeet** [comment] 2022-11-18 18:09
I definitely don't want to remove the type converter defaults - they were added because there was demand for them.
If there's no way of overriding the configuration, that's terrible.

I would strongly *prefer* not to change the default, as that *could* be a breaking change for some users. What I think *would* make sense would be to add patterns that are "just down to minutes, optionally" - that would make it easier to use from code than building the composite pattern yourself, but it doesn't help with the type converter aspect.

**Comment by jsearles** [comment] 2022-11-18 19:07
OK - here is an example app:

https://github.com/jsearles/NodaTimeIssue-1725

If you launch the app, type "03:00:00" you'll see model binding binds the value to the LocalTime property. If you enter "03:00" you'll see that it fails.

**Comment by jskeet** [comment] 2022-11-18 19:12
Right. I'll have a look when I get a chance, but I don't know when that will be.

**Comment by jskeet** [comment] 2022-11-19 08:14
Okay, well it looks like you can use a custom model binder for this fairly easily. Here's something I came up with very quickly based on [the MS documentation](). It *only* handles HH:mm, but you could easily extend it to the composite pattern.

```csharp
internal class CustomLocalTimeBinder : IModelBinder
{
    private static readonly LocalTimePattern pattern = LocalTimePattern.CreateWithInvariantCulture("HH:mm");

    public Task BindModelAsync(ModelBindingContext bindingContext)
    {
        var modelName = bindingContext.ModelName;

        // Try to fetch the value of the argument by name
        var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);

        if (valueProviderResult == ValueProviderResult.None)
        {
            return Task.CompletedTask;
        }

        bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);

        var value = valueProviderResult.FirstValue;

        if (string.IsNullOrEmpty(value))
        {
            return Task.CompletedTask;
        }

        var parseResult = pattern.Parse(value);
        if (parseResult.Success)
        {
            bindingContext.Result = ModelBindingResult.Success(parseResult.Value);
        }
        else
        {
            bindingContext.ModelState.TryAddModelError(
                modelName, parseResult.Exception.Message);
        }

        return Task.CompletedTask;
    }
}
```

You then just need to decorate your model with a property:

```csharp
public class ExampleModel
{
    [BindProperty(BinderType = typeof(CustomLocalTimeBinder))]
    public LocalTime Time { get; set; }
}
```

**Comment by jsearles** [comment] 2022-11-21 17:26
You're right - a custom model binder could resolve this. I was hoping to have this fixed at a lower level as I think TypeConverters have a few other use cases that this wouldn't cover. And since the converter is stricter than the specification, I was hoping there was some room for compromise.

But if the stance of this library is that this should be handled in user-land I will accept that.

**Comment by jskeet** [comment] 2022-11-21 18:04
Yup, I think in general the TypeConverter support is "here are default type converters; they may not be exactly what you want, but if not you need to out how to do configuration for your particular use case". (It varies massively by use case.)

I'll close this issue now, but I've already merged a PR for making more properties available in LocalTimePattern to at least make the user-land code simpler. (Obviously that won't be available until the next release.)

**Closed by jskeet** 2022-11-21 18:04 UTC
Labels: enhancement
