### ISSUE TITLE
American Standard Time Zone Offset Is Incorrect on Xamarin.iOS when using DateTimeZoneProviders.Bcl

### ISSUE THREAD

**Issue by acoats2** [nodatime/nodatime#1691] opened 2022-04-19 01:24 UTC
The following American standard time zone offsets are incorrect on Xamarin.iOS when using DateTimeZoneProviders.Bcl.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/6909518/163900371-5970f9d2-f405-4371-8ccb-1d666d6db9db.png">

I've attached a sample project that allows you to run the unit tests targeting .net 5 and Xamarin.iOS.  Please check out the MockNodaTimeTests in the shared project.  The .net 5 tests run just fine.  On Xamarin.iOS, the tests above fail using the deployed test runner to a simulator, or physical device.

Side note, originally the failure was for daylight saving as I was using NodaTime 3.0.10.  Today 3.1.0 came out and now the daylight saving tests pass, but the standard time tests fail.
[NodaTime310_XamarinIos_TimeZoneIssues.zip](https://github.com/nodatime/nodatime/files/8509016/NodaTime310_XamarinIos_TimeZoneIssues.zip)
.

**Comment by jskeet** [comment] 2022-04-19 05:46
Thanks for the report. It's going to be tricky for me to work on this as the only Mac I have is an ancient Mac Mini which I haven't used for years - I'll see if I'm able to get that up and running again. (I won't be able to do anything until the evening in UK time anyway, mind you.)

I recently overhauled the BclDateTimeZone code very substantially to get it to work for .NET 6 on Linux - I'm still testing on .NET Core 3.1 as well, but I *don't* have any tests for .NET 5.

Are you able to run your tests against .NET 6 and see whether they pass there? If they *do* work on .NET 6, I'm tempted to leave well alone, given how hard it is to "interpret" the `TimeZoneInfo` adjustment rules correctly, and given that .NET 5 will no longer a platform supported by Microsoft as of May 8th. (I'll still see what I can find out in order to write some documentation around it.) If the tests fail under .NET 6 as well, that should at least make it easier to work on.

**Comment by jskeet** [comment] 2022-04-19 19:24
Right - the tests run fine on both .NET 5.0 and .NET 6.0 on my WSL2 installation. I'm currently updating my ancient Mac Mini to see if I can get it installed there...

**Comment by jskeet** [comment] 2022-04-20 07:13
Just for simplicity of me reproducing, here's the test (without any need for `NodaTime.Testing`; requires .NET 6 SDK to build due to the file-scoped namespace declaration):

```csharp
using NodaTime;
using NUnit.Framework;
using System;

namespace NodaTimeSharedTests;

public class BclDateTimeZoneTest
{
    private static readonly DateTime daylightDate = new DateTime(2022, 6, 15, 0, 0, 0, DateTimeKind.Utc);
    private static readonly DateTime standardDate = new DateTime(2022, 1, 15, 0, 0, 0, DateTimeKind.Utc);

    // From https://nodatime.org/TimeZones
    private static string[] AmericanTimeZones =
    {
        "America/Adak", // -10, -9
        "America/Anchorage", // -9, -8
        "America/Boise", // -7,-6
        "America/Chicago", // -6,-5
        "America/Denver", // -7,-6
        "America/Detroit", // -5,-4
        "America/Indiana/Indianapolis", // -5-4
        "America/Indiana/Knox", //	-06, -05
        "America/Indiana/Marengo", //	-05, -04
        "America/Indiana/Petersburg", //	-06, -05, -04
        "America/Indiana/Tell_City", //	-06, -05
        "America/Indiana/Vevay", //	-05, -04	
        "America/Indiana/Vincennes", //	-06, -05, -04
        "America/Indiana/Winamac", // -6,-5,-4
        "America/Juneau", // -9, -8
        "America/Kentucky/Louisville", // -5, -4
        "America/Kentucky/Monticello", // -6, -5, -4
        "America/Los_Angeles", // -8, -7
        "America/Menominee", // -6, -5
        "America/Metlakatla", // -9, -8
        "America/New_York", //	-05, -04
        "America/Nome", //	-09, -08
        "America/North_Dakota/Beulah", //	-07, -06, -05		United States	US	(47.264, -101.778)	Central - ND (Mercer)
        "America/North_Dakota/Center", //	-06, -05		United States	US	(47.116, -101.299)	Central - ND (Oliver)
        "America/North_Dakota/New_Salem", //	-07, -06, -05		United States	US	(46.845, -101.411)	Central - ND (Morton rural)
        "America/Phoenix", //	-07
        "America/Sitka", //	-09, -08
        "America/Yakutat", //	-09, -08
        "Pacific/Honolulu" //	-10
    };
    [Test]
    [TestCaseSource(nameof(AmericanTimeZones))]
    public void TzDb_WhenInDLS_OffsetsMatch(string id) =>
        TestDetails(id, daylightDate, DateTimeZoneProviders.Tzdb[id]);

    [Test]
    [TestCaseSource(nameof(AmericanTimeZones))]
    public void TzDb_WhenInStandardTime_OffsetsMatch(string id)
    {
        TestDetails(id, standardDate, DateTimeZoneProviders.Tzdb[id]);
    }

    [Test]
    [TestCaseSource(nameof(AmericanTimeZones))]
    public void Bcl_WhenInDLS_OffsetsMatch(string id)
    {
        TestDetails(id, daylightDate, DateTimeZoneProviders.Bcl[id]);
    }

    [Test]
    [TestCaseSource(nameof(AmericanTimeZones))]
    public void Bcl_WhenInStandardTime_OffsetsMatch(string id) =>
        TestDetails(id, standardDate, DateTimeZoneProviders.Bcl[id]);

    private void TestDetails(string id, DateTime bclDate, DateTimeZone dateTimeZone)
    {
        var tz = TimeZoneInfo.FindSystemTimeZoneById(id);
        var tzOffset = tz.GetUtcOffset(bclDate);
        var instant = Instant.FromDateTimeUtc(bclDate);
        var nodaOffset = dateTimeZone.GetUtcOffset(instant).ToTimeSpan();
        Assert.AreEqual(tzOffset, nodaOffset);
    }
}
```

**Comment by jskeet** [comment] 2022-04-20 07:53
Okay, the code works on macOS with both .NET 5 and .NET 6. Discussions on Twitter state that Xamarin on .NET 5 on iOS was based on Mono, whereas Xamarin on .NET 6 on iOS is based on the "real" .NET 6, which will have the same time zone code as .NET 6 on macOS... 

So I'm tempted to close this as "won't be a problem once no-one is using Xamarion iOS on .NET 5, and it's too much hassle to try to fix it *for* Xamarin iOS on .NET 5" - is that okay with you, @acoats2?

**Comment by acoats2** [comment] 2022-04-20 17:48
@jskeet - First I wanted to express my appreciation for your work on NodaTime as well as this issue and responses.  You even dug out an old mac mini.

I was speaking to @rlittlesii and it seems the support on Xamarin where this is an issue will be longer than May according to [this](https://devblogs.microsoft.com/dotnet/dotnet-maui-rc-1/) blog post:
![image](https://user-images.githubusercontent.com/6909518/164290515-959c7195-2171-44de-b69e-cbef24630b52.png)

That being said, I get this is a hard problem and it seems like fixing it potentially could break other platforms.

So, if this issue isn't fixed, I'm looking at my options.  One thing my tests did prove is that this is a non-issue if I use the TzDb.  

You mention [here](https://nodatime.org/3.1.x/userguide/mono)
`Noda Time runs on Mono, but its implementation of TimeZoneInfo is known to have some problems, at least on Linux. (Earlier versions had significantly more issues.) If you can use the TZDB time zone provider within Noda Time instead of the BCL one, you're likely to encounter fewer problems.`

What would be the concern about using the TZDB time zone provider instead of the BCL one?

**Comment by jskeet** [comment] 2022-04-20 17:53
> What would be the concern about using the TZDB time zone provider instead of the BCL one?

Very few, if any.

The one *possible* situation where using the BCL version would be "better" is if someone had customized the time zones on their machine, e.g. including extra ones. `DateTimeZoneProviders.Tzdb` won't pick those up, but `DateTimeZoneProviders.Bcl` will.

However, using `DateTimeZoneProviders.Tzdb`:

- The behavior for future dates is generally better, because Noda Time "knows" the actual rules rather than just a set of future transitions
- Noda Time rolls out time zone database changes as NuGet packages within ~12 hours of them being published usually, whereas OS updates can take a long time to be published, then a long time to be installed
- You'll get consistent behavior across all Noda Time installations that use the same database version, regardless of OS

So yes, I'd strongly advise you to use `DateTimeZoneProviders.Tzdb` if at all possible.

**Comment by jskeet** [comment] 2022-04-20 17:56
Finally, I note that Xamarin.iOS 15.2 was released in November 2021 - although bizarrely the [release notes](https://docs.microsoft.com/en-gb/xamarin/ios/release-notes/?WT.mc_id=dotnet-35129-website) don't include that. Given that .NET 6 was released in November 2021 as well, is it possible that that version uses .NET 6? Which version of Xamarin.iOS are you using?

**Comment by acoats2** [comment] 2022-04-20 18:57
Yes, it seems they've stopped publishing to those release notes.  Their [github repo](https://github.com/xamarin/xamarin-macios) does have a little better detail, but even they're out of date.  I ran the test with the tip, Xamarin.iOS 15.8.0.3.

My understanding is .net 6 support comes with MAUI.
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-6#net-maui

**Comment by jskeet** [comment] 2022-04-20 18:59
Okay. I'll see if I can get Mono running under WSL2 when I get some time, and see what it's doing. No promises though...

**Comment by acoats2** [comment] 2022-04-20 19:00
Thank you.

That being said, after this conversation I do believe we'll be looking closer at using the Tzdb impl.

**Comment by jskeet** [comment] 2022-05-01 07:03
I've had another look at this, and basically I believe it would take several hours of messing around just to get Mono building/running against NodaTime - no doubt Xamarin sorts it out somehow, but I haven't got the time to put into this when the result of the investigation is *likely* to be "Wow, the Mono implementation of TimeZoneInfo is really messed up" - so I'm afraid I'm going to close this as infeasible. Hopefully using `DateTimeZoneProviders.Tzdb` will give you everything you need.

**Closed by jskeet** 2022-05-01 07:03 UTC
