### ISSUE TITLE
Transient Failures to Map From BCL TimeZoneInfo To DateTimeZone

### ISSUE THREAD

**Issue by Cooksauce** [nodatime/nodatime#1616] opened 2021-02-05 18:06 UTC
For the following method:
```
        public static DateTimeZone GetNodaTimeZoneFromId(this string timeZoneId)
        {
            var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);
            if (timeZoneInfo is null)
                throw new Exception("Couldn't find timezone id.");

            var dateTimeZone = DateTimeZoneProviders.Bcl.GetZoneOrNull(timeZoneInfo.Id) ??
                throw new Exception($"Couldn't find NodaTime zone for {timeZoneInfo.Id}");

            return dateTimeZone;
        }
```

With the following test:
```
    [TestFixture]
    [Parallelizable(ParallelScope.None)]
    public class NodaBclTimeZoneTest
    {
        [Test]
        [TestCase("America/Indianapolis")]
        [TestCase("Asia/Calcutta")]
        public void GetNodaTimeZoneFromId_ShouldFindTimeZone(string id)
        {
            Action action = () => id.GetNodaTimeZoneFromId();
            
            action.Should().NotThrow();
        }
    }
```

Using Rider w/ built-in test runner, the following test fails when running all tests at once, but not when run individual. The behavior also changes to passing all when using `ParallelScope.All`.

Here's a pass/fail table: (For Brevity - Indianapolis = Case 1, Calcutta = Case 2)
| Run Type | Parallel Scope | Case 1 | Case 2|
| --- | --- | --- | --- |
| Run All | None | Pass | Fail |
| Run Single | None | Pass | Pass |
| Run All | All | Pass | Pass |
| Run Single | All | Pass | Pass |

* NOTE: Every failure is on the 6th line of the method.

Any idea why this is happening?

**Comment by jskeet** [comment] 2021-02-05 18:09
No, I don't understand it - but not knowing what the test failure looks like makes it harder too.

Can you reproduce the same behavior running it via "dotnet test"? (I'd rather not have to install Rider to debug this.) If you could provide a zip file with a minimal project + source code (just one project should be fine - I don't think you should need to separate it into test+prod code) that would make things simpler, rather than me asking about different versions of test runners etc.

**Comment by Cooksauce** [comment] 2021-02-05 18:19
Same behavior with `dotnet test`. I'll get something zipped up

**Comment by Cooksauce** [comment] 2021-02-05 20:05
@jskeet Repro here:

[NodaTimeZoneTest.zip](https://github.com/nodatime/nodatime/files/5934987/NodaTimeZoneTest.zip)

**Comment by jskeet** [comment] 2021-02-05 20:20
Right, reproduced, thanks. Will look into it.

**Comment by jskeet** [comment] 2021-02-05 20:26
Scratch that - I'm running on Windows, so I'm not surprised that none of those time zones are found.
I assume you're running this on Linux?

**Comment by Cooksauce** [comment] 2021-02-05 21:14
Oh yeah sorry:
- MacOS: 10.15
- Runtime: DotNET 3.1 & 5.0

*We are also hitting this issue in production on Linux containers.

**Comment by jskeet** [comment] 2021-02-05 21:25
Mmm. Will look into it.

**Comment by jskeet** [comment] 2021-02-05 21:28
Out of interest, if you're using this on non-Windows machines, is there any reason you're using `DateTimeZoneProviders.Bcl` at all? I'd normally expect that to be used on Windows, for apps that need to use the Windows time zones.

Obviously that doesn't stop it from being a bug - just trying to work out a way around it for you while I fix it :)

**Comment by jskeet** [comment] 2021-02-05 21:31
Next thing - you still haven't told me what the test failure actually *is*. Is it "Couldn't find NodaTime zone for ...", or is an exception thrown within Noda Time, or something else? (Hopefully I'll be able to tell by reproducing it myself at some point, of course...)

**Comment by Cooksauce** [comment] 2021-02-05 21:50
> Out of interest, if you're using this on non-Windows machines, is there any reason you're using DateTimeZoneProviders.Bcl at all? I'd normally expect that to be used on Windows, for apps that need to use the Windows time zones.

^The system was originally designed using the BCL `DateTime` , `TimeZoneInfo`, etc. So what we have saved in the database are timezone ids which are ids from the TimeZoneInfo BCL class. Recent updates w/ more complex date/time transformations led us to use NodaTime for the obvious reasons. In retrospect, we probably should've used NodaTime from the beginning, but we had some concerns about it playing well with EF Core.

> Next thing - you still haven't told me what the test failure actually is.

^The exception is thrown by the `??` operator on this line:
`var dateTimeZone = DateTimeZoneProviders.Bcl.GetZoneOrNull(timeZoneInfo.Id) ??
                               throw new Exception($"Couldn't find NodaTime zone for {timeZoneInfo.Id}");`


#### More...
After digging through NodaTime a bit, I believe I found a workaround as this:
```
public static DateTimeZone GetNodaTimeZoneFromId(this string timeZoneId)
{
    var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);
    if (timeZoneInfo is null)
        throw new Exception("Couldn't find timezone id.");

    return BclDateTimeZone.FromTimeZoneInfo(timeZoneInfo);
}
```

I think this issue is in the cache layer. Potentially, `DateTimeZoneCache.cs` lines 99-102. (_I didn't look too much further into that though_)

**Comment by jskeet** [comment] 2021-02-05 21:57
> So what we have saved in the database are timezone ids which are ids from the TimeZoneInfo BCL class. 

But if you're now running on Linux/Mac, I wouldn't expect it to know about the Windows time zone IDs anyway. (It's possible that .NET Core on Linux/Mac "fakes" the Windows time zone IDs - I haven't checked.)

> I think this issue is in the cache layer. Potentially, DateTimeZoneCache.cs lines 99-102. (I didn't look too much further into that though)

I don't believe it's that section. All the entries are populated in the `DateTimeZoneCache` constructor - just with null values to start with. So it really shouldn't be returning false from that.

I suspect it *may* be from the lines following that:

```csharp
if (zone is null)
{
    zone = source.ForId(id);
    if (zone is null)
    {
        throw new InvalidDateTimeZoneSourceException(
            $"Time zone {id} is supported by source {VersionId} but not returned");
    }
    // 
    return timeZoneMap.TryUpdate(id, zone, null) ? zone : timeZoneMap[id];
}
```

That `return` statement assumes that if `TryUpdate` returns false, that's because another thread has populated the map *and that the new entry will be immediately available after the `TryUpdate` calls has returned*. Maybe that's not a valid assumption.

Assuming I can reproduce this on my Linux box, I should be able to test that...

**Comment by Cooksauce** [comment] 2021-02-05 22:23
> You could potentially call GetZoneOrNull and only fall back to your workaround if it does return null.

Good call here, performance isn't to big of an issue on this anyway.

> But if you're now running on Linux/Mac, I wouldn't expect it to know about the Windows time zone IDs anyway.

We have always deployed on linux, so we don't actually have any Windows ids saved.

I appreciate your help! Let me know if you need any more information/context around this.

**Comment by jskeet** [comment] 2021-02-05 22:29
> We have always deployed on linux, so we don't actually have any Windows ids saved.

Right. I'd recommend using `DateTimeZoneProviders.Tzdb` as the Noda Time representation of IANA time zones is (or certainly was) a more accurate representation of those zones than the `TimeZoneInfo` representation (which has to use the `TimeZoneInfo` adjustment rules). It also probably keeps things rather more up to date, assuming you update the version of NodaTime regularly.

Out of interest, before I get a chance to try to test this myself over the weekend, could you try your existing test but using `DateTimeZoneInfo.Tzdb`? I wonder whether we'll still see the same problem.

Thinking about the cache again, I don't see how that would actually cause the problem with the test you gave me - because it only ever asks for each time zone once. I'm beginning to wonder whether this is actually a problem with `TimeZoneInfo` - that it returns an incomplete set of IDs to start with. But that's really a stretch...

If I *can* reproduce this on my own box, it shouldn't be too hard to then work out what's going on. If I can't reproduce it locally, that's going to make it much harder...

**Comment by jskeet** [comment] 2021-02-06 06:57
Okay, I now have my Linux box up and running, and I can't reproduce the problem. I did have to change the time zones being tested in order to get it to pass at all though - my Linux box doesn't have Asia/Calcutta or either of the "Etc" zones being used in the test. But then the tests just passed.

I really don't know how to move forward with this now :(

**Comment by malcolmr** [comment] 2021-02-06 11:27
I wonder if this is similar to #235, in which `TimeZoneInfo.FindSystemTimeZoneById(id)` was returning a non-null value for a timezone not returned by `TimeZoneInfo.GetSystemTimeZones()`? (Jon: seems like you considered this above. Did you discount it for some reason?)

(In that issue, it was `TimeZoneInfo.Local`, which might or might not be returned by `TimeZoneInfo.GetSystemTimeZones()` - and also might or might not be discoverable via `TimeZoneInfo.FindSystemTimeZoneById(TimeZoneInfo.Local.Id)` - but a similar thing is the only way I can explain what's going on here.)

Anyway, this shouldn't be too hard to test. In your repro, after:

```csharp
var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);
if (timeZoneInfo is null)
    throw new Exception("Couldn't find timezone id.");
```

could you also check that a zone with Id == timeZoneId is present in those zones returned by `TimeZoneInfo.GetSystemTimeZones()`?

If not, that would cause `DateTimeZoneProviders.Bcl.GetZoneOrNull(id)` to return null, since it assumes that it can identify all valid timezones upfront.

**Comment by jskeet** [comment] 2021-02-06 12:08
@malcolmr: That would explain all except the "parallel-only" aspect of the problem. Fingers crossed we'll get there though - your suggested additional diagnostics are still helpful.

**Comment by malcolmr** [comment] 2021-02-06 13:44
Good point. Additional hypothesis: perhaps calling `TimeZoneInfo.FindSystemTimeZoneById(id)` affects the result of the following `TimeZoneInfo.GetSystemTimeZones()` call somehow, such that the invariant is true when executed serially, but not when multiple tests are interleaved?

**Comment by jskeet** [comment] 2021-02-06 13:56
Right - that would definitely have weird impacts. If we get to the stage where I can reproduce the issue, we should be able to test that hypothesis. This is a very odd issue...

**Comment by Cooksauce** [comment] 2021-02-06 22:34
Some more info/comments:
- These id's are ids returned returned by `TimeZoneInfo.GetSystemTimeZones()` on dotnet core `2.1 thru 3.1`, and running on a GKE. The nodes are running `Container-Optimized OS`. (I'm not familiar enough w/ how `TimeZoneInfo` interacts with the OS to know if that matters)
- It's not clear to me this is a "parallel-only" issue. In the fail case you can see that when run with `ParallelScope.All`, the issue is not there. But when running with `ParallelScope.None`, _which runs the tests serially_, the issue appears. Further, with that case running a single test doesn't cause the issue appear. So to fully qualify the conditions, it's - When running multiple tests serially in a single process.

After further isolating the NodaTime method I have found the following very interesting behavior (which seems to point to initializing the BCL provider):

## Simpler Tests:
```
        [Test] // Fails
        public void Test()
        {
            var id1 = "America/Indianapolis";
            var zone1 = DateTimeZoneProviders.Bcl.GetZoneOrNull(id1);
            zone1.Should().NotBeNull();
        }

        [Test] // Passes
        public void Test()
        {
            var id1 = "America/Indianapolis";
            _ = TimeZoneInfo.FindSystemTimeZoneById(id1);
            var zone1 = DateTimeZoneProviders.Bcl.GetZoneOrNull(id1);
            zone1.Should().NotBeNull();
        }

        [Test] // Fails
        public void Test()
        {
            var id1 = "America/Indianapolis";
            var id2 = "Asia/Calcutta";

            _ = TimeZoneInfo.FindSystemTimeZoneById(id1);
            var zone1 = DateTimeZoneProviders.Bcl.GetZoneOrNull(id1);
            _ = TimeZoneInfo.FindSystemTimeZoneById(id2);
            var zone2 = DateTimeZoneProviders.Bcl.GetZoneOrNull(id2);

            zone1.Should().NotBeNull();
            zone2.Should().NotBeNull();
        }

        [Test] // Passes
        public void Test()
        {
            var id1 = "America/Indianapolis";
            var id2 = "Asia/Calcutta";

            _ = TimeZoneInfo.FindSystemTimeZoneById(id1);
            _ = TimeZoneInfo.FindSystemTimeZoneById(id2);
            var zone1 = DateTimeZoneProviders.Bcl.GetZoneOrNull(id1);
            var zone2 = DateTimeZoneProviders.Bcl.GetZoneOrNull(id2);

            zone1.Should().NotBeNull();
            zone2.Should().NotBeNull();
        }
```

So there's some kind of unexpected? side effects between initializing `TimeZoneInfo` & `DateTimeZoneProviders.Bcl`.

Are you able to re-produce those?^

**Comment by jskeet** [comment] 2021-02-06 22:40
I'll try to have a look tomorrow. It may be easy to reproduce this in a Cloud Function. I do wonder whether this *is* TimeZoneInfo being inconsistent in the IDs it returns. That's the only explanation I have at the moment.

**Comment by malcolmr** [comment] 2021-02-06 22:54
In the third test above, where does the failure occur? Is it in the line `zone2.Should().NotBeNull()`?

If so, those results would all be consistent with the hypothesis that `TimeZoneInfo.FindSystemTimeZoneById(id)` is materialising a zone such that it's later returned by `TimeZoneInfo.GetSystemTimeZones()`, and that calls prior to that do not see that zone. (The very first call to `DateTimeZoneProviders.Bcl` within a process will capture the zones that `GetSystemTimeZones()` returns.)

However, you did mention `TimeZoneInfo.GetSystemTimeZones()` as well. Were you able to check what zones it returns, sans any NodaTime code or other calls?

**Comment by Cooksauce** [comment] 2021-02-06 23:09
> In the third test above, where does the failure occur? Is it in the line zone2.Should().NotBeNull()?

@malcolmr Correct - `zone2` is null, `zone1` is not

**Comment by Cooksauce** [comment] 2021-02-06 23:31
### More Behavior:
```
        [Test] // 4. Fails
        public void TimeZoneInfoTest()
        {            
            var hasIndianapolis = TimeZoneInfo.GetSystemTimeZones().Any(o => o.Id == "America/Indianapolis");
            var zone = TimeZoneInfo.FindSystemTimeZoneById("America/Indianapolis");
            var hasIndianapolisAfter = TimeZoneInfo.GetSystemTimeZones().Any(o => o.Id == "America/Indianapolis");

            // TimeZoneInfo.GetSystemTimeZones() == 425
            // "hasIndianapolis" is false here
            // "zone" is not null here

            hasIndianapolisAfter.Should().BeTrue(); // Fails
        }

        [Test] // 5. Passes
        public void TimeZoneInfoTest()
        {
            var zone = TimeZoneInfo.FindSystemTimeZoneById("America/Indianapolis");
            var hasIndianapolis = TimeZoneInfo.GetSystemTimeZones().Any(o => o.Id == "America/Indianapolis");

            // TimeZoneInfo.GetSystemTimeZones() == 426

            zone.Should().NotBeNull();  // passes
            hasIndianapolis.Should().BeTrue();  // passes
        }
```

**Comment by jskeet** [comment] 2021-02-07 07:41
Completely agree with this being a BCL bug. Are you happy to raise an issue with the BCL team about it?

To explain why America/Indianapolis exhibits this: I *suspect* it's aliases in the [backward file](https://github.com/eggert/tz/blob/master/backward) that aren't included until they're requested. My guess is that those are represented by symlinks in the file system, and that whatever BCL code walks the file tree to find the system time zones doesn't include symlinks.

In terms of the Noda Time behavior, I'd really rather not make that change. It feels like it's propagating the poor behavior - and doing so in code which isn't even `TimeZoneInfo`-related. Note that `source.ForId` should never return null - it's documented to throw an exception if the time zone isn't found. (The existing check for zone being null is to protect against bad sources.) So we'd need to catch that to "catch the exception, swallow it, and return null". We'd also then still *not* return the ID in the `Ids` collection, because that's not derived from the map. And we *can't* include it in the `Ids` collection, because we guarantee that's immutable.

Basically we'd be changing from one weird pattern of behavior to another, and I'd prefer not to do that.

I'm honestly not sure the best way to workaround this bizarre BCL behavior right now. Happy to think of other ideas... one horrible option (which doesn't need a change in Noda Time) is to add something in application startup code that first checks whether the BCL supports IANA-like zones (e.g. by checking whether America/New_York is supported) and then fetches all the time zones listed in `TzdbDateTimeZoneSource.Default.Aliases`. If you do that before `DateTimeZoneProviders.Bcl` is first used, everything should be okay. We *could* put the code to do that into NodaTime itself, but I'd be very nervous of doing it automatically as part of the initialization of `DateTimeZoneProviders.Bcl`.

Here's some code which does that:

```csharp
private static void PrepopulateSystemTimeZones()
{
    // Abort early on Windows.
    if (TryGetTimeZoneInfo("America/New_York") is null)
    {
        return;
    }
    
    var aliases = TzdbDateTimeZoneSource.Default.Aliases.SelectMany(id => id);
    foreach (var alias in aliases)
    {
        TryGetTimeZoneInfo(alias);
    }
    
    TimeZoneInfo TryGetTimeZoneInfo(string id)
    {
        try
        {
            return TimeZoneInfo.FindSystemTimeZoneById(id);
        }
        catch (TimeZoneNotFoundException)
        {
            return null;
        }
    }
}
```

**Comment by malcolmr** [comment] 2021-02-07 10:15
(fwiw, I can't see any way to safely fix this in NodaTime either: while we don't _explicitly_ say that a source may not return a zone given an ID that's not present in the `Ids` collection [we only require the converse], we do strongly imply that that should be the case. And, as you mention, the collection of IDs is documented and required to be static.)

**Comment by Cooksauce** [comment] 2021-02-07 19:27
> Completely agree with this being a BCL bug. Are you happy to raise an issue with the BCL team about it?

If you are interested in that, I'm happy let you do it. We have our work-around for production done, and because the perf consideration doesn't matter in our case, there's not much reason for me to spend more time on this. Otherwise, I'll get around to it at some point.

> In terms of the Noda Time behavior, I'd really rather not make that change. It feels like it's propagating the poor behavior

Fair point - and completely reasonable. The workaround we've got is just fine for us, so we don't **need** it anyway.

@jskeet @malcolmr  Thank you both for the help!

**Comment by jskeet** [comment] 2021-02-08 11:29
Happy to leave you to get round to it at some point later - no rush from my side :) Closing this now. Glad it's all sorted for you.

**Closed by jskeet** 2021-02-08 11:29 UTC
