### ISSUE TITLE
Period Between invalid calculation

### ISSUE THREAD

**Issue by famjadbupa** [nodatime/nodatime#1791] opened 2024-03-14 09:56 UTC
Period Between Calculation is wrong.

the following test fails. the period result is Years - 0, Months - 11, Days - 28. This is wrong the difference between these days is 1 less than 1 year. 

        public void Between_LocalDatesWithGivenUnits()
        {
            Period period = Period.Between(
                new LocalDate(2024, 3, 29),
                new LocalDate(2025, 3, 28),
                PeriodUnits.YearMonthDay);

            Assert.AreEqual(0, period.Years);
            Assert.AreEqual(11, period.Months);
            Assert.AreEqual(30, period.Days);
            Assert.AreEqual("P11M28D", period.ToString());
        }

**Comment by jskeet** [comment] 2024-03-14 10:48
No, the calculation is correct. If you add the period of "11 months and 28 days" to 2024-03-29, you get 2025-03-28:

- 2024-03-29 + 11 months = 2025-02-28 (because 2025-02-28 doesn't exist)
- 2025-02-28 + 28 days = 2025-03-28

Adding your expected period of 11 months and 30 days would get to 2025-03-30 instead.

**Comment by famjadbupa** [comment] 2024-03-14 22:09
In this case you are assuming a month is from a day of month to the same day of the next month. Then in the example I have given 1 year is 12 months. and a day before 1 year would depend on the start day of the month.

So in theory, from 2024-03-29 to 2024-03-28, you lost 3 days. because the result is 11 months and 28 days. and if you add 1 day now you have 12 months?

Should the logic be count the complete months from start of month to end of month which in the example would be 11. Then in 2024-03-29 there are 3 days to end of month. then in 2024-03-28 there are 27 days. so 11 full months. 27 + 3 = 30 days.

**Comment by jskeet** [comment] 2024-03-14 22:17
No, that's just not how the calendrical calculation is documented to work in NodaTime. It's been like this forever. There are multiple ways of defining calendrical arithmetic, but I chose a way that was easy to document and easy to understand. It may not be the choice you'd have made, but I believe it's behaving as documented. Do you disagree?

**Comment by jskeet** [comment] 2024-03-19 18:03
Closing as this is working as intended and documented.

**Closed by jskeet** 2024-03-19 18:03 UTC

**Comment by malcolmr** [comment] 2024-03-23 11:30
Just by way of comparison, I'm pretty sure NodaTime uses exactly the same algorithm as java.time's `Period.between()` here.
