### ISSUE TITLE
Website slows down (or halts?) every five minutes

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#755] opened 2017-04-06 16:25 UTC
After #751, we added an external (private) Prometheus/blackbox_exporter setup to probe nodatime.org.

One odd thing I noticed: there appear to be significant (350ms -> 1250ms) spikes at five-minute intervals, but only affecting the user guide / markdown content (I'm using http://nodatime.org/1.3.x/userguide/serialization, and requesting it every minute).

One possible clue: these _appear_ to be the times concurrent with requests for http://nodatime.org/tzdb/tzdb2016f.nzd, though the spikes continue even when we removed one of the NZD files and so that request was returning a 404 (which we did temporarily to test our monitoring).

Note that due to #751, we actually have most of Google Cloud Storage stubbed out at the moment (see cfb0164), so the only part involved should be the specific part that fetches and re-serves the NZD content (https://github.com/nodatime/nodatime/blob/master/src/NodaTime.Web/Models/TzdbDownload.cs).

**Comment by malcolmr** [comment] 2017-04-07 12:20
Oddly, having been reliable for ~8 hours, the regular latency spikes appear to have stopped after 2017-04-07T00:34Z.

I'll take a look in a few days, but perhaps this was something entirely out of our control?

**Comment by malcolmr** [comment] 2017-04-09 09:25
Hasn't recurred, no idea what this was.

**Comment by malcolmr** [comment] 2017-04-13 16:46
Ah, I see what's going on here. Our monitoring hits the website at 1-minute intervals (or 5-minute for the NZD file). Separately, there's some event that occurs globally every five minutes or so, and that appears to cause all content delivery to take over a second, regardless of URL. So if our monitoring happens to sync up with this event, we get what looks like a spike in a single URL, but actually it's the whole site.

**Comment by malcolmr** [comment] 2017-04-13 16:50
Specifically, today I saw a pause across multiple independent requests at:

2017-04-13T17:15:45
2017-04-13T17:40:45

but requests a second earlier and two seconds later were fine, which suggests a 1~2 second event at that point that blocked or significantly delayed request processing.

**Comment by malcolmr** [comment] 2017-04-13 16:51
@jskeet I think you mentioned the GCS fetch was every five minutes. Could you have a look to see whether there's anything obvious in terms of lock contention during that fetch?

**Comment by jskeet** [comment] 2017-04-13 18:05
Will see what I can do, yes. I think it *may* be a lazy cache, i.e. we fetch at most once every 5 minutes. I think I'll change this to make a background fetch every five minutes with an atomic switchover. I'll try to do this in a general way. It's a pity that ASP.NET Core doesn't (as far as I can tell) provide anything like this itself.

**Comment by malcolmr** [comment] 2017-04-19 10:51
fwiw, this isn't fixed. I'm still seeing slowdowns at _exactly_ 5-minute intervals, for any request.

(which is interesting, since we changed the GCS cache timeouts, so it clearly isn't that.)

I also checked whether this was a problem at my end by probing from two different endpoints at once; same results from both at the same time.

From my home machine:

```
2017-04-19T11:06:02,535146243+0100 http://nodatime.org/ 200 0.004 0.108 0.108 0.228 0.339
2017-04-19T11:06:03,538190527+0100 http://nodatime.org/ 200 0.004 0.107 0.107 0.233 0.338
2017-04-19T11:06:04,545826519+0100 http://nodatime.org/ 200 0.004 0.108 0.108 1.068 1.926
2017-04-19T11:06:05,548745317+0100 http://nodatime.org/ 200 0.004 0.111 0.111 0.927 1.034
2017-04-19T11:06:06,550443766+0100 http://nodatime.org/ 200 0.004 0.107 0.108 0.237 0.341
2017-04-19T11:06:07,551741023+0100 http://nodatime.org/ 200 0.004 0.113 0.113 0.223 0.327

2017-04-19T11:06:03,537035850+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.107 0.107 0.221 0.490
2017-04-19T11:06:04,544309725+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.108 0.108 1.066 2.010
2017-04-19T11:06:05,548532103+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.108 0.108 0.941 1.155
2017-04-19T11:06:06,549334224+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.108 0.108 0.237 0.449
2017-04-19T11:06:07,551293382+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.107 0.107 0.230 0.440
```

From a machine at work:

```
2017-04-19T11:06:00,546589774+0100 http://nodatime.org/ 200 0.004 0.100 0.100 0.231 0.327
2017-04-19T11:06:01,554697148+0100 http://nodatime.org/ 200 0.004 0.098 0.098 0.235 0.329
2017-04-19T11:06:02,566578976+0100 http://nodatime.org/ 200 0.004 0.099 0.099 0.231 0.329
2017-04-19T11:06:03,576384051+0100 http://nodatime.org/ 200 0.004 0.099 0.099 0.224 0.318
2017-04-19T11:06:04,580782199+0100 http://nodatime.org/ 200 0.004 0.097 0.097 0.824 1.904
2017-04-19T11:06:05,585067004+0100 http://nodatime.org/ 200 0.004 0.099 0.099 0.884 0.995
2017-04-19T11:06:06,588926018+0100 http://nodatime.org/ 200 0.004 0.099 0.099 0.210 0.314
2017-04-19T11:06:07,602359976+0100 http://nodatime.org/ 200 0.004 0.100 0.100 0.221 0.318

2017-04-19T11:06:02,566122215+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.100 0.100 0.233 0.425
2017-04-19T11:06:03,576633935+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.098 0.098 0.220 0.407
2017-04-19T11:06:04,580983547+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.099 0.100 0.827 1.987
2017-04-19T11:06:05,584506027+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.099 0.100 0.899 1.094
2017-04-19T11:06:06,587615058+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.099 0.099 0.213 0.402
2017-04-19T11:06:07,602976148+0100 http://nodatime.org/1.3.x/userguide/serialization 200 0.004 0.100 0.100 0.221 0.412
```

(timings are various timing outputs from `curl`; the last two are `time_starttransfer` and `time_total`, showing that the delay appears to be happening both before and during the requests.)

**Comment by jskeet** [comment] 2017-04-19 10:54
That's very odd indeed. Later this quarter let's try to run the site on Container Engine and see if we get the same effect. Maybe it's just an Azure oddity somehow, although that seems unlikely.

**Comment by jskeet** [comment] 2017-04-19 10:58
It doesn't look like it's due to traffic - I can see a big 45-minute-long spike which I assume was you testing (and then a bigger but brief spike just recently) but there's no sign of an "every 5 minutes" spike.

**Comment by malcolmr** [comment] 2017-04-19 11:07
Yes, 10:14-10:56 and 11:04-11:07 (Europe/London) are me.

I saw pauses at 10:16:04, 10:21:04. 10:26:04, 10:31:04, ... 11:06:04.

**Comment by jskeet** [comment] 2017-04-21 16:23
Do you still have your script, and is it small enough to include in a comment here? Would like to try running it against my local machine (or another machine running on my network) and would rather not reinvent the wheel.

**Comment by malcolmr** [comment] 2017-04-21 19:24
Behold my hacky scripts:

```sh
$ cat fetch
#!/bin/sh

readonly TS=$(date -Ins)
readonly URL=$1
readonly BASE_FILENAME=$(echo "${TS}-${URL}" | tr '/' '_')
readonly TRACE_FILENAME=${BASE_FILENAME}.trace
readonly LOG_FILENAME=${BASE_FILENAME}.log
echo -n "${TS} " > ${LOG_FILENAME}
curl -L --trace-ascii ${TRACE_FILENAME} --trace-time -s -o /dev/null -w '%{url_effective} %{http_code} %{time_namelookup} %{time_connect} %{time_pretransfer} %{time_starttransfer} %{time_total}\n' ${URL} >> ${LOG_FILENAME}
$ cat fetch-many 
#!/bin/sh

readonly FETCH=$(dirname $0)/fetch

${FETCH} http://nodatime.org/tzdb/tzdb2016f.nzd &
${FETCH} http://nodatime.org/tzdb/latest.txt &
${FETCH} http://nodatime.org/api/NodaTime.Duration.html &
${FETCH} http://nodatime.org/1.3.x/userguide/serialization &
${FETCH} http://nodatime.org/ &
$ cat fetch-loop 
#!/bin/sh

while /bin/sleep 1; do
  $(dirname $0)/fetch-many
done
$
```

Invoke with `./fetch-many` and wait for a bit. Produces one `.log` and one `.trace` file per request(!), so you probably want to combine them with something like `cat *.log | sort | less` (or make that `sort | sort -k2,2` to split them up by URL).

**Comment by jskeet** [comment] 2017-04-23 18:34
Well, I've managed to reproduce it at home against nodatime.org, so that's at least a start. Now to try it with a local server...

**Comment by jskeet** [comment] 2017-04-23 19:24
Interesting - no sign of this locally. I might try running the same test against other sites I'm running on Azure...

**Comment by jskeet** [comment] 2017-04-24 13:06
I've seen the same thing to a lesser extent (and with less consistent timing) on jonskeet.uk. Very odd.

**Comment by jskeet** [comment] 2018-05-19 09:40
Given that we're planning on moving away from Azure to Google Kubernetes Engine, I'm going to close this as effectively obsolete. (I doubt that we'll want to spend time fixing it on Azure before we move.)

**Closed by jskeet** 2018-05-19 09:40 UTC
Labels: low priority, website
