### ISSUE TITLE
GetSystemDefault fails to get time zone on non-English localizations of Windows.

### ISSUE THREAD

**Issue by chaniev** [nodatime/nodatime#413] opened 2015-12-09 16:30 UTC
Hello
i use DateTimeZoneProviders.Tzdb.GetSystemDefault().Id for get default system timezone, but sometimes on different computers i get error

if don't install http://support.microsoft.com/kb/2998527

NodaTime.TimeZones.DateTimeZoneNotFoundException: TimeZoneInfo ID Московское время (зима) is unknown to source TZDB: 2014e (mapping: 9723)
   at NodaTime.TimeZones.DateTimeZoneCache.GetSystemDefault()

"Московское время (зима)"  is "Moskow time (winter)" on english

or if install 
NodaTime.TimeZones.DateTimeZoneNotFoundException: TimeZoneInfo ID "RTZ 2 (зима)" is unknown to source TZDB: 2014e (mapping: 9723)
   at NodaTime.TimeZones.DateTimeZoneCache.GetSystemDefault()

on my computer (i have install http://support.microsoft.com/kb/2998527) DateTimeZoneProviders.Tzdb.GetSystemDefault().Id return Europe\Moskow

**Comment by jskeet** [comment] 2015-12-09 17:29
Ick. This is the problem with TimeZoneInfo.Id sometimes being localized. It's a real pain.

So just to be clear, *all* you're doing is calling `DateTimeZoneProviders.Tzdb.GetSystemDefault().Id`?

@mj1856 Any thoughts?

**Comment by chaniev** [comment] 2015-12-09 20:08
yes, it's  Windows 7 x64 Russian localization
i use only DateTimeZoneProviders.Tzdb.GetSystemDefault().Id

there are recommendation step by step search between the different various installation Windows?

**Comment by jskeet** [comment] 2015-12-09 20:42
I don't know, I'm afraid - but Matt may have some other ideas (and ways in which we could avoid this being a problem). Personally I think it shows that the `Id` property is really implemented in an entirely broken way, but we can't change that in Noda Time...

**Comment by mj1856** [comment] 2015-12-09 21:52
Time zone IDs are not supposed to be localized.  I could see it happening in code that mistakenly called `TimeZoneInfo.StandardName` instead of `TimeZoneInfo.Id` - especially in places where the `Id` and `FindSystemTimeZoneById` APIs were not available (such as from Silverlight).  But other than that, I'm not sure how it could happen.

Similarly, the TZDB id will always be `Europe/Moscow`.  `Europe\Moskow` is invalid due to both the spelling and direction of the slash.

**Comment by mj1856** [comment] 2015-12-09 21:55
Uggh.. looks like we're doing that for PCL.  I forgot about this.  Mentioned in the [limitations page](http://nodatime.org/1.3.x/userguide/limitations.html).

**Comment by mj1856** [comment] 2015-12-09 21:58
For clarification, `StandardName`, `DaylightName`, and `DisplayName` all come directly from the Windows registry, and thus reflect the OS language setting.

**Comment by jskeet** [comment] 2015-12-09 22:01
Yup, I remember seeing it in the PCL, but this is the first time I've heard about it happening on regular Windows.

@chaniev: What kind of .NET project is this? Can you reproduce it in a straightforward desktop framework console app?

**Comment by mj1856** [comment] 2015-12-09 22:04
Searching for `StandardName` I see some places where we use `#if` to use `Id` when available, and other places where we just use `StandardName`.  This should be refactored to a single location.  The one that's likely the culprit is probably [here](https://github.com/nodatime/nodatime/blob/1.3.x/src/NodaTime/TimeZones/BclDateTimeZone.cs#L83)

**Comment by mj1856** [comment] 2015-12-09 22:15
Without `TimeZoneInfo.Id` and without registry access, the only way I can see making this work is with either 1) including all localizations in a mapping table, or 2) algorithmic detection similar to jsTimeZoneDetect - which would be imperfect but better than nothing.

While the first option seems daunting on the surface, it may actually be possible to compute a minimal set of substrings to check for.  I'll think about this some more...

**Comment by mj1856** [comment] 2015-12-09 22:17
Another way, of course, is what we discussed in chat before, which would only work on systems where `new Windows.Globalization.Calendar().GetTimeZone()` is available to return the TZDB id.

**Comment by chaniev** [comment] 2015-12-10 07:50
thanks, for answers

sorry, DateTimeZoneProviders.Tzdb.GetSystemDefault().Id of course return Europe\Moscow, it's my mistake when post message

i use Net Framework 4.0 full version, not Client Profile
NodaTime file version 1.3.0.0

**Comment by chaniev** [comment] 2015-12-10 11:36
create console test application and run on computers with problem and get:

TimeZoneInfo DaylightName: RTZ 2 (лето)
TimeZoneInfo DisplayName: RTZ 2 (зима)
TimeZoneInfo Id: RTZ 2 (зима)
TimeZoneInfo StandardName: RTZ 2 (зима)

om my computer

TimeZoneInfo DaylightName: RTZ 2 (лето)
TimeZoneInfo DisplayName: (UTC+03:00) Волгоград, Москва, Санкт-Петербург (RTZ 2)
TimeZoneInfo Id: Russian Standard Time
TimeZoneInfo StandardName: RTZ 2 (зима)

**Comment by mj1856** [comment] 2015-12-10 14:55
Are those just from `TimeZoneInfo.Local` or are they through Noda Time?  I'm very surprised about the display name.  Are you sure that this machine hasn't had the registry manually edited?  Are its Windows updates current?

**Comment by mj1856** [comment] 2015-12-10 15:00
Also, what does `tzutil.exe /g` return?

**Comment by chaniev** [comment] 2015-12-11 09:11
yes, from TimeZoneInfo.Local

**Comment by chaniev** [comment] 2015-12-11 12:18
i am imported from problem computers registry path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Russian Standard Time to my computer and console test utility return correct value TimeZoneInfo

**Comment by chaniev** [comment] 2015-12-14 10:36
I received a similar result on your computer:

TimeZoneInfo DaylightName: RTZ 2 (лето)
TimeZoneInfo DisplayName: RTZ 2 (зима)
TimeZoneInfo Id: RTZ 2 (зима)
TimeZoneInfo StandardName: RTZ 2 (зима)

and exception

NodaTime.TimeZones.DateTimeZoneNotFoundException: TimeZoneInfo ID "RTZ 2 (зима)" is unknown to source TZDB: 2014e (mapping: 9723)

after delete registry path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Russian Standard Time

can be a problem on the other computer occurs due to lack of rights the user has read the register?

**Comment by jskeet** [comment] 2016-11-15 10:27
Need to investigate this again... it's possible there was a .NET bug which has been fixed, but let's check.

**Comment by jskeet** [comment] 2016-12-29 17:39
@chaniev: Do you still have this problem? It's quite hard to pinpoint what's wrong.

**Comment by jskeet** [comment] 2017-02-25 08:16
Closing for now as unreproducible.

**Closed by jskeet** 2017-02-25 08:16 UTC
Labels: bug
