### ISSUE TITLE
Period.Between days value is incorrect?

### ISSUE THREAD

**Issue by JJ-Jiang** [nodatime/nodatime#1236] opened 2018-12-11 02:24 UTC
Hi, tested with the following:

var f = new DateTime(2019,03,01);
	var t = new DateTime(2019,04,01);
	var fromDate = new LocalDate(f.Year,f.Month,f.Day).PlusDays(-1);
	var toDate = new LocalDate(t.Year,t.Month,t.Day);
	
	var period = Period.Between(fromDate,toDate);
It seems as long as it starts from 01/March (doesn't matter which year), the result of period.days value is wrong. 

Thanks

**Comment by jskeet** [comment] 2018-12-11 06:07
What result did you expect to get, and what result did you actually get? Note that fromDate isn't March 1st - it's Feb 28th, due to your PlusDays call. (I don't know why you're using DateTime at all here, mind you ...)

**Comment by JJ-Jiang** [comment] 2018-12-11 23:18
Hi Jskeet, 
Thanks for your reply. 
The code was just an extraction from some old codes, some doesn't make sense here, I am just lazy to change it. 
My question is actually if I make it as fromDate =(2019,01,01), toDate = (2019,01,31), and I get 1 Month which is correct.
If I make it as fromDate =(2019,03,01), toDate = (2019,03,31), then I get 1 Month and 3 days, but shouldn't it be 1 Month only as well?

Thanks

**Comment by jskeet** [comment] 2018-12-12 06:11
Rather than being lazy, please provide a complete example. It sounds like you're actually taking the period between the end of the previous month and the "to" date. From February 28th to March 31st *is* one month and 3 days... If you add one month to February 28th, you get March 28th. You then need to add another 3 days to get to March 31st.

Closing as it sounds like everything is working as intended.

**Closed by jskeet** 2018-12-12 06:11 UTC
