### ISSUE TITLE
ZoneInterval.Name for Etc zones

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#361] opened 2015-03-31 00:54 UTC
Usually, the `ZoneInterval.Name` is a time zone abbreviation, such as `PST` or `PDT`.  But for zones starting with `Etc/`, it is the full name of the zone.

```csharp
Console.WriteLine(tzdb["Etc/UTC"].GetZoneInterval(now).Name);
Console.WriteLine(tzdb["Etc/GMT"].GetZoneInterval(now).Name);
Console.WriteLine(tzdb["Etc/GMT-1"].GetZoneInterval(now).Name);
Console.WriteLine(tzdb["Etc/GMT+1"].GetZoneInterval(now).Name);
```

Gives:
```
Etc/UTC
Etc/GMT
Etc/GMT-1
Etc/GMT+1
```

I would expect:
```
UTC
GMT
GMT+1
GMT-1
```

(Note the sign reversal)

**Comment by jskeet** [comment] 2015-04-02 13:57
In terms of sign, this follows what the IANA comments say:

```
# We use POSIX-style signs in the Zone names and the output abbreviations,
# even though this is the opposite of what many people expect.
# POSIX has positive signs west of Greenwich, but many people expect
# positive signs east of Greenwich.  For example, TZ='Etc/GMT+4' uses
# the abbreviation "GMT+4" and corresponds to 4 hours behind UT
# (i.e. west of Greenwich) even though many people would expect it to
# mean 4 hours ahead of UT (i.e. east of Greenwich).
```

I'm surprised it's showing the "Etc/" part though.

**Comment by jskeet** [comment] 2015-04-02 14:20
Okay, I've worked out the "Etc/" part - fixed-offset zones only have an ID and offset, not a name. I think this probably counts as a bug, although it's going to be a pain to fix up - we'll need to consider how to extend the serialization format to include the name.

I suggest I raise a separate bug for that, but then close this one as (otherwise) working as intended - we're providing the interpretation of the data that IANA intends, even if it's somewhat annoying. (I'm not sure that just arbitrarily changing the names would be better, as then anyone who *did* know what to expect would get confused.)

**Comment by mj1856** [comment] 2015-04-02 18:02
Yep, I would agree then.

**Comment by jskeet** [comment] 2015-04-02 18:03
Added issue #363; closing this one.

**Closed by jskeet** 2015-04-02 18:03 UTC
