### ISSUE TITLE
Can create LocalDate with 0 or -1 day 

### ISSUE THREAD

**Issue by DmitryMak** [nodatime/nodatime#806] opened 2017-05-02 19:47 UTC
I expect these lines to throw an ArgumentOutOfRangeException:

new LocalDate(2014, 1, -1);
new LocalDate(2014, 1, 0);

Actual result is that instances get created but are unusable (calling ToString on them throws IndexOutOfRangeException for example). This is latest stable from NUget (NodaTime 2.0.0)

**Comment by jskeet** [comment] 2017-05-02 19:49
Duplicate of #801.

**Closed by jskeet** 2017-05-02 19:49 UTC
