### ISSUE TITLE
Confusing naming for NodaTime.Extensions.IsoDayOfWeekExtensions.ToIsoDayOfWeek

### ISSUE THREAD

**Issue by samcic** [nodatime/nodatime#880] opened 2017-06-28 11:22 UTC
From: http://nodatime.org/2.0.x/api/NodaTime.Extensions.IsoDayOfWeekExtensions.html

This extension method takes an IsoDayOfWeek and returns a DayOfWeek. I would have hence thought it should be named "ToDayOfWeek" rather than "ToIsoDayOfWeek". Perhaps I'm missing something obvious...

**Comment by jskeet** [comment] 2017-06-28 11:27
Duplicate of https://github.com/nodatime/nodatime/issues/776

**Closed by jskeet** 2017-06-28 11:27 UTC
