### ISSUE TITLE
Null reference when calling DateTimeZoneProvider.GetSystemDefault()

### ISSUE THREAD

**Issue by RandomEngy** [nodatime/nodatime#638] opened 2017-01-28 00:11 UTC
I've gotten this crash report for my Xamarin Android app. It appears to be hitting a null ref when trying to get the current time zone.

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
NodaTime.LocalDate.Previous(IsoDayOfWeek targetDayOfWeek)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.ZoneYearOffset.MakeInstant(int year, Offset standardOffset, Offset savings)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.ZoneYearOffset.Next(Instant instant, Offset standardOffset, Offset savings)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.ZoneRecurrence.Next(Instant instant, Offset standardOffset, Offset previousSavings)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.ZoneRecurrence.NextOrFail(Instant instant, Offset standardOffset, Offset previousSavings)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.DaylightSavingsDateTimeZone.FindMatchingRecurrence(Instant instant)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.DaylightSavingsDateTimeZone.GetZoneInterval(Instant instant)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.PrecalculatedDateTimeZone.GetZoneInterval(Instant instant)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.CachingZoneIntervalMap.HashArrayCache.HashCacheNode.CreateNode(int period, IZoneIntervalMap map)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.CachingZoneIntervalMap.HashArrayCache.GetZoneInterval(Instant instant)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.CachedDateTimeZone.GetZoneInterval(Instant instant)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.DateTimeZone.<GetZoneIntervals>d__41.MoveNext()<0282c821be1c4b988d9176f1dd0a191f>:0
System.Linq.Enumerable.<SelectManyIterator>c__Iterator2<TSource, TResult>.MoveNext()<dd5df878dcd54cd1bece18f177bbd090>:0
System.Linq.Enumerable.WhereSelectEnumerableIterator<TSource, TResult>.MoveNext()<dd5df878dcd54cd1bece18f177bbd090>:0
System.Linq.Enumerable.<DistinctIterator>c__Iterator12<TSource>.MoveNext()<dd5df878dcd54cd1bece18f177bbd090>:0
System.Collections.Generic.List<T>.List(IEnumerable<T> collection)<657b9f6cac8f48938c7a8e0fd1a21258>:0
System.Linq.Enumerable.ToList<TSource>(IEnumerable<T> source)<dd5df878dcd54cd1bece18f177bbd090>:0
NodaTime.TimeZones.TzdbDateTimeZoneSource.GuessZoneIdByTransitionsUncached(TimeZoneInfo zone)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.TzdbDateTimeZoneSource.GuessZoneIdByTransitions(TimeZoneInfo zone)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.TzdbDateTimeZoneSource.MapTimeZoneId(TimeZoneInfo zone)<0282c821be1c4b988d9176f1dd0a191f>:0
NodaTime.TimeZones.DateTimeZoneCache.GetSystemDefault()<0282c821be1c4b988d9176f1dd0a191f>:0
```

**Comment by jskeet** [comment] 2017-01-28 13:15
Hmm. Xamarin's time zone handling is generally broken (or has been historically), but I'd be surprised to see it manifest itself in this way.

Which version of Noda Time are you using? If you're able to try the 2.0 beta, that would be great - the code has changed a lot since 1.3.

**Comment by RandomEngy** [comment] 2017-01-28 15:52
Yes this is 1.3. It's not a common crash and it comes only from crash reports so I'd need to release with 2.0 beta to find out if it's fixed. Trying to decide if it that's a good idea or not; as it might cause a bigger problem when upgrading the logic or give me a different bug.

**Comment by jskeet** [comment] 2017-01-28 21:34
Thanks for the detail. I'll have to have a look at the 1.3 code. I wasn't *planning* on doing any more 1.3 releases though - we'll have to see what I find.

**Comment by jskeet** [comment] 2017-01-29 19:15
Okay, I've looked at the code and I can't see how we'd end up with a `NullReferenceException` with that stack trace... it just makes no sense to me. (I'm not disputing the stack trace itself - just that I don't understand it!) The call from `ZoneYearOffset.MakeInstant` to `LocalDate.Previous` makes sense, but that shouldn't throw a `NullReferenceException`.

I'm not sure what to suggest at this point... if you catch the exception, are you able to continue e.g. by asking the user for their time zone? If you could log any extra information so we can try to find a pattern that would help us reproduce the problem, that would be great, but I quite understand if you can't.

Sorry not to be more use here... I just don't understand :(

**Comment by RandomEngy** [comment] 2017-01-30 21:04
Well it's not a large crash bucket right now. I'll keep an eye on it and add some logging if I can think of what may help.

**Comment by jskeet** [comment] 2017-03-15 10:30
Closing for now as we can't really do anything - please reopen with more info if you get any.

**Closed by jskeet** 2017-03-15 10:30 UTC
