### ISSUE TITLE
Support serialization of DateTimeZone

### ISSUE THREAD

**Issue by VelocityDB** [nodatime/nodatime#978] opened 2017-10-03 00:01 UTC
Something happened between NodaTime version 1.x and 2,2 that  is causing a serializtion error.
A C# class containing a single field as below

  public class NodaTest2
  {
    private DateTimeZone _timeZone;

    public NodaTest2()
    {
      _timeZone = DateTimeZone.Utc;
    }
  }

Part of serializing this object and its time zone field is 

![image](https://user-images.githubusercontent.com/1156765/31104520-47169012-a792-11e7-9a73-37bb37670287.png)

The problem is that this Instant IsValid is false but your code throws an exception since days is out of range. Maybe skip check if IsValid is false?

Original data when serialized has the same value for days as far I can see from debugging so looks to me that DateTimeZone.UTC is serialized and de serialized correctly (in this case by VelocityDB code)

**Comment by jskeet** [comment] 2017-10-03 06:11
It's unclear why serializing `DateTimeZone.Utc` would serialize any instants at all.

If this is the binary serializer, `DateTimeZone` doesn't support binary serialization at all as far as I can see. Could you provide a complete example we could use to reproduce this? I'm surprised it got even this far.

**Comment by VelocityDB** [comment] 2017-10-03 22:17
Thanks for responding Jon. I attached a test case for using VelocityDB for binary serialization/deserialization and also a NewtonJson test case. Both failing.
If you need access to src for VelocityDB, it can be arranged.

[NodaTimeTest.zip](https://github.com/nodatime/nodatime/files/1354067/NodaTimeTest.zip)

**Comment by jskeet** [comment] 2017-10-04 06:34
Hmm. Basically, I'd never intentionally written any serialization for `DateTimeZone` - even when it was working with NodaTime 1.x, it wasn't really doing the right thing, in that it would break invariants... if you serialized `DateTimeZone.Utc`, you wouldn't deserialize back to `DateTimeZone.Utc`.

I think the best way to proceed is to treat this issue as a request for `DateTimeZone` to be serializable. We'll just serialize it by ID, deserializing by looking up the ID in the relevant provider. That's what we do with `ZonedDateTime` for example.

I'm surprised that binary serialization isn't complaining that it's trying to serialize something that isn't marked as being serializable though...

**Comment by VelocityDB** [comment] 2017-10-04 15:27
In general, NewtonJason and VelocityDB will attempt to serialize regardless of type being marked as   [Serializable]  and doing so successfully most of the time. Anyway, yes consider adding DateTimeZone as a  [Serializable] as my client in Australia is using it that way. Doing it by id sounds good. In this case the failure really was with [Serializable] Type: Instant so I modified the test to make it fail serializing an object of that type.
[NodaTimeTest.zip](https://github.com/nodatime/nodatime/files/1356372/NodaTimeTest.zip)

**Comment by jskeet** [comment] 2017-10-04 15:59
Eek - that's surfaced a rather more worrying issue, which is that this code:

```csharp
Instant.MinValue.Minus(Duration.FromDays(1))
```

should throw an exception to start with. One of the things I worked hard on for 2.0 was trying to prevent invalid values creeping out. I've filed #979 for that, and will get to that urgently, hopefully releasing a 2.2.1 with the fix. That *won't* solve the `DateTimeZone` issue though, I'm afraid.

**Comment by jskeet** [comment] 2017-10-04 17:15
Just to get a measure of the urgency here, is your client experimenting with upgrading to Noda Time 2.x, or do they definitely need to do so in the very near future?

**Comment by VelocityDB** [comment] 2017-10-04 21:31
I asked my client, who says: 
"NodaTime is an integral part of an application which generates realistic synthetic data for testing and evaluating law enforcement and intelligence systems. Class instances are persisted using VelocityDB and NodaTime is used for all date and time related information. DateTimeZone is used to record the time zone of each city, so that local times can be calculated from Instant. While there is an definite intention to upgrade to 2.2, there is no great urgency. DateInterval is one of the main reasons for upgrading, however we have created a similar class that has the same behaviour as an interim measure."

**Comment by jskeet** [comment] 2017-10-05 06:33
Thanks for the information. I'll try to get to it pretty quickly.

One thing to note is that any data serialized with 1.x will not be deserializable with 2.x - so if your client as a lot of persisted serialized data, they'll need to work out how to deal with that incompatibility. I'm happy to try to help work out a migration process, but backward compatibility would have been painful and fragile.

The good news is that when we *do* serialize DateTimeZone via the zone ID, it'll result in a much, much smaller serialized size. (There are other aspects to be aware of in terms of tzdb versioning, but that's a different matter.)

**Comment by jskeet** [comment] 2017-10-05 07:09
(I've modified the subject line to indicate what the issue has effectively turned into - hope that's okay with you. I could revert it then create a new issue if you'd prefer.)

**Comment by VelocityDB** [comment] 2017-10-05 08:07
My client says backwards compatibility is not an issue at this time as they are able to regenerate the data from scratch, yes smaller data is good news. In general Iserializable classes do add some extra bookkeeping vs classes that  can be serialized without but I think for DateTimeZone Iserializable makes sense. Thanks for this.

**Comment by jskeet** [comment] 2017-10-09 06:32
Looking into this, there are a few issues we need to consider:

- I don't believe we can support XML serialization; it doesn't have the equivalent of `GetRealObject` that binary serialization does
- We need to investigate whether it "sort of" works in JSON for some time zones. (I'll test that.) If it already works and we change it to work *differently*, we'll be breaking backwards compatibility.
- I don't think we need to worry about binary serialization in the same way, as it doesn't normally serialize at all using binary serialization, as `DateTimeZone` isn't marked as being serializable. If VelocityDB chooses to do things outside the normal serialization framework, I don't mind breaking that - it's not something we've ever claimed to support
- Should we distinguish between provider-based zones and others? For `ZonedDateTime`, we just ask the current serialization provider for the zone with the same ID. That will (in 2.x) prefer the provider's zone over fixed zones. Sometimes that's what you want, sometimes it's not... it's unfortunate that a `ZonedDateTime` in UTC won't always have a time zone of `DateTimeZone.Utc` after deserialization, even if it had it before... on the other hand, changing that behaviour for `ZonedDateTime` now could break other users. (In JSON it's even harder to know what to do, as the serialized form is more visible.) We could be inconsistent here between `ZonedDateTime` and `DateTimeZone` if necessary, but that's ugly too. Urgh :(

**Comment by jskeet** [comment] 2017-10-09 06:32
cc @malcolmr - see comment above as context for our discussion later :)

**Comment by VelocityDB** [comment] 2017-10-09 21:55
DateTimeZone.Utc works what looks like correctly if you just don't throw in
        private Instant([NotNull] SerializationInfo info, StreamingContext context)
        {
            duration = new Duration(info);
            // Duplication of code in Instant.FromUntrustedDuration,
            // because we can't chain to a static method...
            int days = duration.FloorDays;
            if (days < MinDays || days > MaxDays)
            {
              //  throw new OverflowException("Operation would overflow range of Instant");
            }
        }
Throwing here seams wrong as this how its used internally with DateTimeZone.Utc .
Or make it nullable and use a null value instead of an invalid Instant? If enforcing singleton instances isn't an issue then this change and mark classes [Serializable] will work for VelocityDB but NewtonJson expects a default constructor with no parameters for each serialized object which is missing in this case.

**Comment by jskeet** [comment] 2017-10-10 06:04
No, I don't want to ever serialize or deserialize a beginning of time or end of time instant. Those should never be exposed to users. Throwing is entirely intentional.

Serialization for Noda Time is *not* intended to go through default paths of just assigning to properties or calling constructors. It's intended to go through the custom paths provided - and in this case, there simply isn't a `DateTimeZone` path. I would far rather provide one than become laxer around what's valid serialized data.

**Comment by jskeet** [comment] 2018-05-19 08:11
I'm removing binary serialization entirely from Noda Time 3.0. It's actively discouraged by Microsoft now.

Closing as we're not intending to address this.

**Closed by jskeet** 2018-05-19 08:11 UTC
Labels: enhancement
