### ISSUE TITLE
"Europe/Dublin" Daylight saving offset incorrect in version 3.1.0

### ISSUE THREAD

**Issue by QualityCodePassion** [nodatime/nodatime#1692] opened 2022-05-26 07:25 UTC
Hi, for some reason when we updated our NodaTime nuget package from "2.2.3" to "3.1.0" our unit test picked up a bug for the "Europe/Dublin" Daylight saving offset for the DateTime "2022-12-07T22:56:56". Below is a code snippet containing hard-coded values to show an example of the test case is failing.

In version 2.2.3 the "daylightSavingsOffset" value below used to be equal to 0, but after updating to version 3.1.0 it's now returning -3600, which we believe to be incorrect. If anyone is able to fix this bug for us that would be greatly appreciated!

```
// Code snippet
var dateTimeZoneProvider = DateTimeZoneProviders.Tzdb;
var timeZone = dateTimeZoneProvider.GetZoneOrNull("Europe/Dublin");
var parsedLocalTime = LocalDateTimePattern.GeneralIso.Parse("2022-12-07T22:56:56");

var zoneDateTime = parsedLocalTime.Value.InZoneLeniently(timeZone);
var localInstant = zoneDateTime.GetZoneInterval();
var daylightSavingsOffset = localInstant.Savings.Seconds;   // returns -3600, but expecting 0
```

**Comment by jskeet** [comment] 2022-05-26 07:39
No, that's correct. What you're observing is that 2.2.3 is very old - it shipped with TZDB 2017c.

In the 5 years since then, the Europe/Dublin rule has changed - in particular, in [this commit](https://github.com/eggert/tz/commit/b266263699ab1b02d7d4b7307e5303181bea00c1).

Ireland observes standard time in the summer, and negative daylight saving time in the winter. From the [Wikipedia article](https://en.wikipedia.org/wiki/Time_in_the_Republic_of_Ireland):

> In Ireland, the Standard Time Act 1968 legally established that the time for general purposes in the State (to be known as standard time) shall be one hour in advance of Greenwich mean time throughout the year. This act was amended by the Standard Time (Amendment) Act 1971, which legally established Greenwich Mean Time as a winter time period. Ireland therefore operates one hour behind standard time during the winter period, and reverts to standard time in the summer months. This is defined in contrast to the other states in the European Union, which operate one hour ahead of standard time during the summer period, but produces the same end result.

Note that this only affects the daylight savings aspect of the offset - I wouldn't expect you to see any difference in the offset from UTC.

Closing as this is all working as intended.

**Closed by jskeet** 2022-05-26 07:39 UTC

**Comment by QualityCodePassion** [comment] 2022-05-31 07:00
Thank you very much for your excellent explanation and helpful references @jskeet and apologies for jumping to the wrong conclusion without doing a proper google search, I can now see you have answered this question in the past.
