### ISSUE TITLE
BclDateTimeZone not available for netstandard 2.0

### ISSUE THREAD

**Issue by tsuttmann** [nodatime/nodatime#1400] opened 2019-07-15 08:40 UTC
Hey,
i am starting using NodaTime for my netstandard 2.0 class libaries. I was surprised that essential types like `BclDateTimeZone` are missing. What are the reasons behind this? I currently retrieving the UtcOffset from `TimeZoneInfo` and applying a conversion to UTC with the DotNet Bcl APIs which is not very pleasant.

**Comment by jskeet** [comment] 2019-07-15 08:46
This is working as intended. We introduced netstandard2.0 support in NodaTime 2.4.0 with this release note:

> The NuGet package explicitly supports .NET Standard 2.0 now. This uses the same build as for .NET Standard 1.3 (no support for BclDateTimeZone) but gives a better installation experience when using a platform supporting it. When targeting the full .NET Framework, the .NET 4.5 build will still be picked up.

Even though netstandard2.0 contains the APIs required for supporting BclDateTimeZone, getting it to work correctly on non-Windows platforms required significant work, which is now in the 3.x codebase.

If you need to use a netstandard build but use `TimeZoneInfo`, you could use the 3.x alpha release - I'd be happy to create an initial beta at this stage if that would be useful (as the alpha build is pretty old now). The 3.x codebase only targets netstandard2.0. (It's possible that we'll introduce a netstandard2.1 target over time; that's still TBD.)

**Comment by tsuttmann** [comment] 2019-07-15 09:16
Thanks for the quick reply. I guess the stable 3.x release will take some time? Is the roadmap https://nodatime.org/developer/roadmap still up to date? 
I will probably encapsulate the missing bits in internal types until a stable version of 3.x is available.

**Comment by jskeet** [comment] 2019-07-15 10:10
Yes, the roadmap is broadly correct, although I should probably update it a bit. 3.x is *at least* gated by C# 8 getting a full release, but I would like to get the Span support in as well for parsing and formatting. At the moment I don't know how I'd do that in an additive manner... if we *can* delay that until 3.1, that would unblock 3.0. I might give that a try soon.

It's probably worth pointing out that the 3.x code is at least as robust as the 2.x code, as far as I'm aware. While there may be some small API changes, I don't think they'll be large - so if I were to do a beta release, you should feel pretty confident in it.

Closing this issue now as I've hopefully answered the question.

**Closed** 2019-07-15 10:14 UTC
