### ISSUE TITLE
Unable to LocalDate Property on ModelBind with Json.Net and WebApi

### ISSUE THREAD

**Issue by ahmettaha** [nodatime/nodatime#352] opened 2015-03-16 04:45 UTC
Hello,

I have a model class with a single property in it. The property is of type "LocalDate". No matter, what I do the model binder doesnt bind the date. How do I make LocalDate and ZonedDateTime bind automaticaly like other types?

I was successfully able to disable validation. Otherwise, it was causing an error as in bug #249 
I have added Json.NET library from nuget. So I'm able to serialize them without any problems.

**Comment by jskeet** [comment] 2015-03-16 13:25
How are you configuring Json.NET? You'd need to tell it to ignore its own DateTime conversions, and to use the ones in the NodaTime.Serialization.JsonNet library.

**Comment by ahmettaha** [comment] 2015-03-16 15:18
I have this for serialization


            jsonFormatter.SerializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);

and this to fix the validation errors

 WebApiConfig.Services.Replace(typeof(IBodyModelValidator), new CustomBodyModelValidator());

public class CustomBodyModelValidator : DefaultBodyModelValidator
    {
        public override bool ShouldValidateType(Type type)
        {
            return type.Namespace != "NodaTime" && base.ShouldValidateType(type);
        }
    }

**Comment by jskeet** [comment] 2015-03-16 15:27
So just to check, this is a model that you're receiving as a *request*, and that's not being populated from the request data? Is the JSON formatter you're configuring definitely the one being used for deserialization? If you are able to come up with a minimal example, I'd love to try to reproduce it and dig into what's going on.

**Comment by ahmettaha** [comment] 2015-03-16 15:31
this is how I do the settings.

```
            var jsonFormatter = new JsonMediaTypeFormatter();

            jsonFormatter.SerializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);

            WebApiConfig.Services.Replace(typeof(IContentNegotiator), new JsonContentNegotiator(jsonFormatter));
            WebApiConfig.Services.Replace(typeof(IBodyModelValidator), new CustomBodyModelValidator());

            app.UseWebApi(WebApiConfig);


    public class JsonContentNegotiator : IContentNegotiator
    {
        private readonly JsonMediaTypeFormatter _jsonFormatter;

        public JsonContentNegotiator(JsonMediaTypeFormatter formatter)
        {
            _jsonFormatter = formatter;
        }

        public ContentNegotiationResult Negotiate(Type type, HttpRequestMessage request, IEnumerable<MediaTypeFormatter> formatters)
        {
            var result = new ContentNegotiationResult(_jsonFormatter, new MediaTypeHeaderValue("application/json"));
            return result;
        }
    }

    public class CustomBodyModelValidator : DefaultBodyModelValidator
    {
        public override bool ShouldValidateType(Type type)
        {
            return type.Namespace != "NodaTime" && base.ShouldValidateType(type);
        }
    }
```

below is my sample request

```
{
amount: 5,
logDate:"2015-02-17",
userLogtime:"2015-02-17T23:06:39"
}
```

below is my model

```
public class LogModelBase : ModelBase
    {
        public LocalDate LogDate { get; set; }

        public LocalDateTime UserLogTime { get; set; }
}

 public class WaterLogModel : LogModelBase
    {
        public int Amount { get; set; }
}
```

below is my webapi controller action
```
 public WaterLogModel Post([FromBody]WaterLogModel model)
```

**Comment by jskeet** [comment] 2015-03-16 15:33
Okay, and is UserLogTime working, but LogDate isn't? Or are neither of them working?

**Comment by ahmettaha** [comment] 2015-03-16 15:47
neither of them are working. they are showing 1970-01-01. However Amount binds without any problems

**Comment by jskeet** [comment] 2015-03-16 15:49
Okay, will try to reproduce. I'm a Web API noob though... if you're able to put together a zip file with a ready-to-run minimal example, that would be really helpful. If not, I'll see what I can do with the above :)

**Comment by ahmettaha** [comment] 2015-03-16 15:55
I'll preapare you a zip file.

**Comment by ahmettaha** [comment] 2015-03-16 16:03
you can download it from

http://expirebox.com/download/f6ebd2d55d70b202d3c668da2f0054dc.html

**Comment by ahmettaha** [comment] 2015-03-16 16:03
you can send the same json example to the following url

http://localhost/api/values

**Comment by jskeet** [comment] 2015-03-16 16:06
Wonderful, thanks. Will experiment on the way home.

**Comment by jskeet** [comment] 2015-03-16 19:32
Got it. It turns out there are two different instances of `JsonMediaTypeFormatter` involved - one for reading, and one for writing. You need to configure both of them.

In your `WebApiConfig.cs`, just add:

```csharp
config.Formatters.JsonFormatter.SerializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
```

and all should work well. I won't close this bug until I've added some documentation.

**Comment by jskeet** [comment] 2015-03-16 20:11
As an update to the above, I'm not sure when the content negotiator is actually used... just changing the `config.Formatters.JsonFormatter.SerializerSettings` seems to be enough...

**Comment by ahmettaha** [comment] 2015-03-16 22:05
it has worked. thank you very much. I have one suggestion though.

If the property is localdate, and if I post "2015-02-17T23:06:39" . it doesnt seem to bind. I think it should still bind but ignore the time part.

**Comment by jskeet** [comment] 2015-03-16 22:07
I'd expect that to throw an error, personally - just like if the property is an int and you provide a value of 12.5, I'd expect that to throw an error too.

Basically, your client and your server should really know what kind of information they're exchanging - if one of them expects a date, and the other wants to pass in a date and time, chances are they've got bigger problems than just binding.

**Comment by ahmettaha** [comment] 2015-03-16 22:18
makes sense.

**Comment by jskeet** [comment] 2015-03-17 09:10
Added a bit more documentation, although it's hard to be specific as there are so many different potential contexts.

**Closed by jskeet** 2015-03-17 09:10 UTC
