### ISSUE TITLE
OffsetDateTimePattern "o" documentation error.

### ISSUE THREAD

**Issue by TheMightyPope** [nodatime/nodatime#1285] opened 2019-02-17 01:56 UTC
From documentation:
o: Extended invariant ISO-8601 pattern, down to the tick. This will round-trip values except for the calendar system. This corresponds to the custom pattern yyyy'-'MM'-'dd'T'HH':'mm':'ss;FFFFFFFo&lt;G&gt;

It appears the actual format is: yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFo&lt;G&gt;

----> Semicolon should be a '.' after 'ss'
Sample result: "2018-11-08T04:49:01.068-08"

Most likely same problem for "r", but I didn't test it.

**Comment by jskeet** [comment] 2019-02-17 09:02
The pattern really does have the `;` in. Note that a `;` signifier is *formatted* as `.`, but will parse both `,` and `.`. (See https://nodatime.org/unstable/userguide/localtime-patterns)
That's so that it can parse any ISO-8601 value, including ones like `2018-11-08T04:49:01,068-08`

Perhaps that's the cause of the misunderstanding?

**Comment by malcolmr** [comment] 2019-02-17 10:36
(For background, see issue #140.)

**Comment by TheMightyPope** [comment] 2019-02-18 18:12
Oh good grief, I swear DateTime Formatting will be the death of me. Sorry, I didn't realize a ';' could be interpreted. I was outputting, not parsing, and thought a literal ';' would be inserted. The page doesn't mention what the output will be (comma or dot), so I never even thought to look up the semicolon.

**Comment by jskeet** [comment] 2019-02-18 19:49
Closing as working as intended.

**Closed by jskeet** 2019-02-18 19:49 UTC
