### ISSUE TITLE
TimeZone.AtStartofDate for day with switch to DLS in Brazil

### ISSUE THREAD

**Issue by Stoffelche** [nodatime/nodatime#1524] opened 2020-04-29 12:27 UTC
In my code I have the following method:

```csharp
public DateTime GetUtcStartOfDay(DateTime day) {
 return TimeZone.AtStartOfDay(new NodaTime.LocalDate(day.Year, day.Month, day.Day)).ToDateTimeUtc();
}
```

for 2012/10/21 I would assume that it returns UTC 2012-10-21-03:00 as the time is advanced in Brazil 1 hour but nothing happened yet with respect to UTC.<br/>
Then for the following day 2012/10/22 I would assume to get UTC 2012-10-22-02:00 as the missing hour leads to the shorter day 21.<br/>
However for 2012/10/21 I get instead: 2012-10-21-02:59:59.999,  which is 1 ms less then expected.
This millisecond is already missing iin the AtStartOfDay result, so I assume something is wrong here?
For the following day 22 I get the full hour as expected.<br/>
Same applies for all other years for the day where the 1 hour is advanced.<br/>
BTW I use BclDateTimeZone.

**Comment by jskeet** [comment] 2020-04-29 13:04
> BTW I use BclDateTimeZone.

I suspect that's the problem. `TimeZoneInfo` behaves weirdly in all kinds of ways. I'll look into it - but I strongly suspect that if you use the TZDB data instead, it'll work fine.

**Comment by jskeet** [comment] 2020-04-29 13:08
Complete example:

```csharp
using System;
using NodaTime;
using NodaTime.Text;

class Test
{
    static void Main()
    {
        var zone = DateTimeZoneProviders.Bcl["E. South America Standard Time"];
        var date = new LocalDate(2012, 10, 21);
        var zoned = zone.AtStartOfDay(date);
        Console.WriteLine(ZonedDateTimePattern.ExtendedFormatOnlyIso.Format(zoned));
    }
}
```

**Comment by jskeet** [comment] 2020-04-29 13:14
I *suspect* the problem is that `TimeZoneInfo` uses "23:59:59.999" to represent a transition at midnight of the following day. I'll need to investigate whether our behavior actually matches `TimeZoneInfo`, or whether we just need to "round up".

**Comment by Stoffelche** [comment] 2020-04-29 13:15
for now I patched it the following way:
`		public DateTime GetUtcStartOfDay(DateTime day) {
			DateTime dt = TimeZone.AtStartOfDay(new NodaTime.LocalDate(day.Year, day.Month, day.Day)).ToDateTimeUtc();
// for Brazil on day of DLS switch TimeZon.AtStartOfDay looses a millisecond
			long seconds = dt.Ticks / TimeSpan.TicksPerSecond;
			if (seconds * TimeSpan.TicksPerSecond < dt.Ticks)
				dt = new DateTime((seconds + 1) * TimeSpan.TicksPerSecond, DateTimeKind.Utc);
			return dt;
		}
`

**Comment by jskeet** [comment] 2020-05-02 12:19
Thanks very much for raising this. It's fixed in master, and will go out as part of 3.0 (or the next beta). I won't be backporting it to 2.x.

**Closed** 2020-05-02 12:18 UTC
Labels: bug

**Comment by Stoffelche** [comment] 2020-05-03 08:58
Thanks for fixing. When will v3.0 be released?

**Comment by jskeet** [comment] 2020-05-03 10:28
I'm hoping it'll be *reasonably* soon - hopefully some time within May - but there are a few last bits of binary compatibility that we're looking at first.
