### ISSUE TITLE
Consider moving factory methods from BclDateTimeZone to BclDateTimeZoneSource

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#218] opened 2015-03-15 09:19 UTC
```
For the TZDB source, we can obtain a DateTimeZone via:

TzdbDateTimeZoneSource source;
DateTimeZone zone = source.ForId(id);

For the BCL source, we can use:

BclDateTimeZoneSource source;
BclDateTimeZone zone = source.ForId(id);

(note the covariant return value)

or we can use:

BclDateTimeZone zone = BclDateTimeZone.ForSystemDefault();
BclDateTimeZone zone = BclDateTimeZone.FromTimeZoneInfo(timeZoneInfo);

I can somewhat understand why, but the For/From bothers me for a start, and I 
wonder whether it'd be clearer to put these on BclDateTimeZoneSource; in 
particular, it'd probably make explaining why 
DateTimeZoneCache.GetSystemDefault() can potentially fail easier (because it 
calls BclDateTimeZoneSource.MapTimeZoneId / ForId).

This might not be worth doing (we'd need to obsolete the existing methods, for 
example), but I thought I'd raise it for future discussion.
```

Original issue reported on code.google.com by `malcolm.rowe` on 4 May 2013 at 9:45

**Comment by jskeet** [comment] 2018-04-02 17:40
@malcolmr: 5 years later, given the lack of other requests for this, do you think we should just close this?
(I'm going to at least remove the "bug" label as it all seems to be working as intended...)

**Comment by malcolmr** [comment] 2018-04-03 07:44
I think it's reasonable to close this: this was just an inconsistency I noticed during the initial API review, and it's a pretty minor one at that.

**Closed by malcolmr** 2018-04-03 07:44 UTC
Labels: enhancement, low priority
