### ISSUE TITLE
Inclusive Interval Duration

### ISSUE THREAD

**Issue by devonbuckingham** [nodatime/nodatime#1548] opened 2020-05-22 20:19 UTC
One issue I have run into using NodaTime is that the duration of an interval is from the number of ticks in the interval, rather than the number of ticks in the interval _plus one_.

For example, if I had an interval whose start was the first tick of May 22nd, 2020, and whose end was the last tick of May 22nd, 2020, then the duration of that interval would _not_ be equal to `Duration.FromDays(1)`; it would be equal to `Duration.FromDays(1) - Duration.Epsilon`. In this case, I would likely want the duration from the _beginning_ of the first tick to the _end_ of the last tick, rather than the number of ticks.

Is there a design reason for this? Is there motivation to add something like `Interval.DurationInclusive`?

**Comment by jskeet** [comment] 2020-05-22 20:25
Closing as a duplicate of #1547

**Closed by jskeet** 2020-05-22 20:25 UTC

**Comment by devonbuckingham** [comment] 2020-05-22 20:34
@jskeet Sorry about that, was having issues with GitHub giving me 500 and accidentally submitted twice

**Comment by jskeet** [comment] 2020-05-22 20:41
No problem. I'll add a comment on the other issue tomorrow.
