### ISSUE TITLE
Display bug in LocalDate

### ISSUE THREAD

**Issue by JvSSD** [nodatime/nodatime#1636] opened 2021-06-09 11:03 UTC
I have found an interesting bug in how `LocalDate` is displayed/`ToString`ed

To showcase it, take the following code:
```var minimumDate = LocalDate.MinIsoValue;
var lateDate = new LocalDate(9999, 01, 01);
var minimumYear = minimumDate.Year;
var longDateInterval = new DateInterval(minimumDate, new LocalDate(2021, 09, 01));
var allDays = longDateInterval.ToList();
var firstYear = longDateInterval.First().Year;
```

When inspecting the variables, the below is what is shown. `minimumYear` and `firstYear` are both correctly -9998, yet according to what the debugger displays, `LocalDate.MinIsoValue` is 9999-01-01 and the next days appear to be the following days, until you appear to go from 9999-12-31 to 9998-01-01.

The day of the week, however, does seem to be correct, given that it is different for `LocalDate.MinIsoValue` and `new LocalDate(9999, 01, 01)`.
![image](https://user-images.githubusercontent.com/54601698/121342512-fcf5c100-c921-11eb-8c41-6f13491e35fd.png)

**Comment by jskeet** [comment] 2021-06-09 11:31
I'm finding this issue hard to understand, partly because it's mixing several things - the debugger, `ToString()`, `DateInterval` etc. (And the code you've quoted is incomplete without `minimumDate` which is visible in the screenshot, but not included in the copy...) For future issues, it would be really helpful if you could provide a minimal console application (so not relying on the debugger, unless this is *only* a problem in the debugger), along with details of the version of NodaTime (and .NET) that you're using.

Fortunately, I've been able to reproduce the issue:

```csharp
using NodaTime;
using System;

class Program
{
    static void Main(string[] args)
    {
        var date = LocalDate.MinIsoValue;
        string text = date.ToString();
        Console.WriteLine(text);
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.0.5" />
  </ItemGroup>

</Project>
```

I strongly suspect this is a matter of the BCL date pattern using "yyyy" which means "year-of-era" which is indeed 9999 for `LocalDate.MinIsoValue`. As the BCL doesn't support values before 1AD, they don't need to distinguish between year-of-era and absolute year.

**Comment by jskeet** [comment] 2021-06-09 11:46
Actually, I take that back about not having to distinguish between year-of-era and absolute year: the Japanese calendar supports multiple eras, and "yyyy" returns the year-of-era. Here's an example:

```csharp
using System;
using System.Globalization;

class Program
{
    static void Main()
    {
        var date = new DateTime(2021, 6, 9);
        var culture = CultureInfo.CreateSpecificCulture("jp-JP");
        var calendar = new JapaneseCalendar();
        culture.DateTimeFormat.Calendar = calendar;
        Console.WriteLine(date.ToString("yyyy-MM-dd", culture));
    }
}
```

The result is 03-06-09, because we're in year 3 of the current era.

So while the result may be unexpected, I believe NodaTime is actually behaving correctly here. I would recommend users who want to deal with BCE dates should probably use `LocalDatePattern.Iso`, or a custom date/time format that uses `uuuu` instead of `yyyy`.

**Comment by JvSSD** [comment] 2021-06-09 19:55
So maybe although the BCL date pattern works correctly, `ToString()`ing a `LocalDate` produces a rather unexpected result because the era information is lost. I wouldn't have been surprised a bit if I would have seen something like 'Tuesday, 01 January 9999 BC'.

**Comment by jskeet** [comment] 2021-06-09 20:00
Sure - but the era information is lost in the Japanese example too.

I can definitely see how it's not ideal - but given that we're taking the default format from the BCL, and it chooses not to include the era, I suspect that any change in Noda Time would make things worse in other ways.

(I expect relatively few applications will be using dates before 1AD though, and I'd hope that they'd consider their date format carefully.)

**Comment by jskeet** [comment] 2021-07-04 06:39
Closing, as I believe there's nothing here to change in Noda Time.

**Closed by jskeet** 2021-07-04 06:39 UTC
