### ISSUE TITLE
Calling Instant.FromUtc(2024, 2, 29, 12, 0) results in a out of range exception

### ISSUE THREAD

**Issue by mleaming** [nodatime/nodatime#1803] opened 2024-06-12 12:28 UTC
Even though this is a valid date for the year 2024, I get an out of range exception with the message "Valid values are 1-28". Since 2024 is a leap year, 29 is a valid day.

**Comment by jskeet** [comment] 2024-06-12 12:51
I can't reproduce this. Here's a complete program:

```csharp
using NodaTime;

var instant = Instant.FromUtc(2024, 2, 29, 12, 0);
Console.WriteLine(instant);
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.11" />
  </ItemGroup>

</Project>
```

Output:

```text
2024-02-29T12:00:00Z
```

Please provide a similarly complete repro that shows the exception you're describing.

**Comment by jskeet** [comment] 2024-06-13 15:40
Closing as we have no information to reproduce this. (If you *can* reproduce this, please add a comment and I'll reopen.)

**Closed by jskeet** 2024-06-13 15:40 UTC

**Comment by mleaming** [comment] 2024-06-14 15:30
I’ll send sample code when I get to a computer.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
