### ISSUE TITLE
Add static class with custom date and time format for different types

### ISSUE THREAD

**Issue by juchom** [nodatime/nodatime#1814] opened 2024-09-12 12:33 UTC
Hello Jon,

Again, thanks for the time you have taken to help on this issue : https://stackoverflow.com/questions/78966329/aspnet-razor-pages-form-local-datetime-not-working-with-nodatime-localdatetime/78975001#78975001

To solve my issue of having `LocalDateTime` plays nicely with input type `datetime-local` in a Razor Pages project we add to do two things to make sure the format is always `yyyy-MM-ddTHH:mm`:

When the page is rendered we add to add the `asp-format` in order to have the `ToString()` format it correctly for the input.

```html
<input asp-for="@Model.Local" type="datetime-local" asp-format="{0:uuuu-MM-dd'T'HH:mm}"/>
```

And when the form is sent back to the server we add to create a custom `TypeConverter` from the `TypeConverterBase<T>` (which needs to make this base class public instead of internal)

```csharp
public class CustomLocalDateTimeConverter : TypeConverterBase<LocalDateTime>
{
    public CustomLocalDateTimeConverter()
        : base(LocalDateTimePattern.CreateWithInvariantCulture("uuuu-MM-dd'T'HH:mm")) { }
}
```

And then register it like this

```csharp
TypeDescriptor.AddAttributes(typeof(LocalDateTime), new TypeConverterAttribute(typeof(CustomLocalDateTimeConverter)));
```

I was wondering if it would make sense to add a static class where we could override the default format for each NodaTime types.

And make the `ToString()`, the `TypeConverter` and `JsonSerializer` would get the default format from this class.

```csharp
public static class NodaTimeFormat
{
    public static string LocalDateTime = "uuuu'-'MM'-'dd'T'HH':'mm':'ss";
    
    public static string LocalDate = "uuuu'-'MM'-'dd";
    
    public static string LocalTime = "HH':'mm':'ss;FFFFFFFFF";
}
```

If this makes sense it would allow to configure the global format for each type at a central point.

**Comment by jskeet** [comment] 2024-09-12 12:38
This is effectively a duplicate of https://github.com/nodatime/nodatime/issues/1765, I believe - and my objections to it are the same as there. Global mutable state is bad in all kinds of ways. We've got it in a *few* places already, but I don't want to add any more.

Making `TypeConverterBase<>` public (after some design review) would make sense, but I don't want to add the public mutable state.

**Comment by juchom** [comment] 2024-09-12 13:07
Actually you ask the right question there :

> how would you configure this without Noda Time, if you were using just DateTime and DateTimeOffset?

And we would have the same issue if we wanted to override the default format.

**Comment by juchom** [comment] 2024-09-13 07:46
Adding a static class is definitly not the right answer to my question, the issue is not with NodaTime at all.

The mistake I made was to think, NodaTime can be used like DateTime and DateTimeOffset in aspnet.

But I forgot that to have NodaTime working with System.Text.Json, Json.Net, SqlServer, NpgSql there are some additional nuget packages.

The missing part in my case would probably be some TagHelpers and some other components to make it work in aspnet like DateTime and DateTimeOffset.

This has nothing to do with NodaTime at all.

Again thanks for your help.

**Comment by jskeet** [comment] 2024-09-28 09:15
Having raised #1817 for the specific change we do want to make, I'll close this issue.

**Closed by jskeet** 2024-09-28 09:15 UTC

**Comment by juchom** [comment] 2024-10-01 08:54
Thanks Jon again !

There is one more thing that may be a problem for end users is if they want to specify the json format serialization also in aspnet.

It's not directly linked to this repository but more to `Nodatime.Serialization`

You answered this question here : https://stackoverflow.com/a/68189757/1026105

I'm not sure if there is a good solution for this.

**Comment by jskeet** [comment] 2024-10-01 09:15
@juchom: I'm not quite sure what problem you're asserting here. It's easier now to configure one converter separately (using `NodaJsonSettings`, introduced in the last release). Please file a detailed separate issue if you think there's still more work to do, but it doesn't sound like it's related to the topic of *this* issue.
